Removed rascal-shell-unstable.jar from repo. Will be downloaded additionally

diff --git a/support/bin/rascalu b/support/bin/rascalu
--- a/support/bin/rascalu
+++ b/support/bin/rascalu
@@ -1,3 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 BASEDIR=$(dirname "$0")
-java -Xmx2G -Xss32m -cp "$BASEDIR/rascal-shell-unstable.jar:$BASEDIR/gson-2.7.jar:$BASEDIR/tcp-server.jar:$BASEDIR/yaml.jar:$BASEDIR/../../src:." org.rascalmpl.shell.RascalShell $@
+RASCAL_JAR="$BASEDIR/rascal-shell-unstable.jar"
+if [ ! -f $RASCAL_JAR ]; then
+    echo "Rascal REPL is needed in order to run Glagol DSL. This dependency is downloaded additionally"
+    read -p "Do you want to conitnue with downloading rascal-shell-unstable.jar from http://rascal-mpl.org? (Y/y/n): " -r
+    echo
+    if [[ $REPLY =~ ^[Yy]$ ]]
+    then
+        wget -O $RASCAL_JAR http://update.rascal-mpl.org/console/rascal-shell-unstable.jar -q --show-progress
+    else
+        echo "Rascal REPL is required to run Glagol DSL. Exiting..."
+        exit 1
+    fi
+fi
+java -Xmx2G -Xss32m -cp "$RASCAL_JAR:$BASEDIR/gson-2.7.jar:$BASEDIR/tcp-server.jar:$BASEDIR/yaml.jar:$BASEDIR/../../src:." org.rascalmpl.shell.RascalShell $@
